"""

Revision ID: 000
Revises: 
Create Date: 2026-02-01 21:27:09.350169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS data;")
    op.execute("CREATE SCHEMA IF NOT EXISTS lookup;")
    op.execute("CREATE SCHEMA IF NOT EXISTS audit;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SCHEMA IF EXISTS data;")
    op.execute("DROP SCHEMA IF EXISTS lookup;")
    op.execute("DROP SCHEMA IF EXISTS audit;")
    # ### end Alembic commands ###
