"""Init

Revision ID: 001
Revises: 
Create Date: 2026-02-01 21:27:09.350169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = '000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_index(op.f('ix_data_organization_slug'), 'organization', ['slug'], unique=True, schema='data')
    op.create_table('control',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('ACCESS_CONTROL', 'ENCRYPTION', 'MONITORING', 'CHANGE_MANAGEMENT', 'INCIDENT_RESPONSE', 'RISK_ASSESSMENT', 'PHYSICAL_SECURITY', 'DATA_PROTECTION', 'NETWORK_SECURITY', 'OTHER', name='controlcategory'), nullable=False),
    sa.Column('control_type', sa.Enum('TECHNICAL', 'ORGANIZATIONAL', 'PHYSICAL', name='controltype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lookup'
    )
    op.create_index(op.f('ix_lookup_control_code'), 'control', ['code'], unique=True, schema='lookup')
    op.create_table('framework',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', 'DRAFT', name='frameworkstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_framework_code_version'),
    schema='lookup'
    )
    op.create_index(op.f('ix_lookup_framework_code'), 'framework', ['code'], unique=False, schema='lookup')
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence_type', sa.Enum('SCREENSHOT', 'DOCUMENT', 'LOG_EXPORT', 'ATTESTATION', 'CONFIGURATION', 'POLICY', 'OTHER', name='evidencetype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'AWS', 'GITHUB', 'OKTA', 'OTHER', name='evidencesource'), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['data.organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    op.create_table('orgframework',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETE', 'NOT_APPLICABLE', name='compliancestatus'), nullable=False),
    sa.Column('adopted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['lookup.framework.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['data.organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'framework_id', name='uq_org_framework'),
    schema='data'
    )
    op.create_table('frameworkcontrol',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('framework_control_code', sa.String(length=50), nullable=False, comment='Framework-specific control code (e.g., CC6.1, Req 3.5.1)'),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['lookup.control.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['framework_id'], ['lookup.framework.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id', 'control_id', name='uq_framework_control'),
    schema='lookup'
    )
    op.create_table('orgcontrol',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('org_framework_id', sa.UUID(), nullable=False),
    sa.Column('framework_control_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETE', 'NOT_APPLICABLE', name='compliancestatus'), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_control_id'], ['lookup.frameworkcontrol.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_framework_id'], ['data.orgframework.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_framework_id', 'framework_control_id', name='uq_org_control'),
    schema='data'
    )
    op.create_table('controlevidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('org_control_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['data.evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_control_id'], ['data.orgcontrol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controlevidence', schema='data')
    op.drop_table('orgcontrol', schema='data')
    op.drop_table('frameworkcontrol', schema='lookup')
    op.drop_table('orgframework', schema='data')
    op.drop_table('evidence', schema='data')
    op.drop_index(op.f('ix_lookup_framework_code'), table_name='framework', schema='lookup')
    op.drop_table('framework', schema='lookup')
    op.drop_index(op.f('ix_lookup_control_code'), table_name='control', schema='lookup')
    op.drop_table('control', schema='lookup')
    op.drop_index(op.f('ix_data_organization_slug'), table_name='organization', schema='data')
    op.drop_table('organization', schema='data')
    # ### end Alembic commands ###
