"""Removed effective date column

Revision ID: 002
Revises: 001
Create Date: 2026-02-01 21:43:48.497706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('framework', 'effective_date', schema='lookup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('framework', sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True), schema='lookup')
    # ### end Alembic commands ###
