"""Added new enums in ControlCategory

Revision ID: 003
Revises: 002
Create Date: 2026-02-02 00:37:08.807943

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE controlcategory ADD VALUE IF NOT EXISTS 'SECURITY_OPERATIONS'")
    op.execute("ALTER TYPE controlcategory ADD VALUE IF NOT EXISTS 'RISK_MANAGEMENT'")
    op.execute("ALTER TYPE controlcategory ADD VALUE IF NOT EXISTS 'BUSINESS_CONTINUITY'")
    op.execute("ALTER TYPE controlcategory ADD VALUE IF NOT EXISTS 'GOVERNANCE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
