"""Removed owner_id column

Revision ID: 004
Revises: 003
Create Date: 2026-02-02 09:03:11.977011

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "004"
down_revision: Union[str, None] = "003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orgcontrol", "owner_id", schema="data")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orgcontrol",
        sa.Column("owner_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        schema="data",
    )
    # ### end Alembic commands ###
